name: intellij_tourism_designer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  js: ^0.7.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  data_table_2: ^2.5.12
  latlong2: ^0.9.1
  url_launcher: ^6.2.5
  flutter_map_geojson: ^1.0.8
  logger: ^2.2.0
  provider: ^6.1.2
  fl_chart: ^0.67.0
  easy_date_timeline: ^1.0.7
  calendar_date_picker2: ^1.1.5
  dio: ^5.5.0+1
  oktoast: ^3.4.0
  pull_to_refresh: ^2.0.0
  flutter_swiper_view: ^1.1.8
  material_floating_search_bar_2: ^0.5.0
  flutter_localization: ^0.2.1
  window_manager: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/json/test_data/
    - assets/imgs/
